# Local Development Environment only (Not for dev in AWS and prod)

services:

  # Spring Boot Application Container
  backend:
    container_name: springboot
    build: .
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - dev-network

  # RabbitMQ Container
  rabbitmq:
    container_name: rabbitmq
    command: "rabbitmq-plugins enable rabbitmq_stomp" # Enable STOMP plugin in RabbitMQ
    image: rabbitmq:4.1.0-management-alpine
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
      - "15674:15674" # STOMP
      - "61613:61613" # STOMP Listen
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test123
      - RABBITMQ_DEFAULT_VHOST=seatcatcher
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
        - dev-network

networks:
  dev-network:
    driver: bridge