name: Integration

on:
  branches:
    - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # 추후 ECR 생성 후 추가 예정