name: slack-alarm.yml
on:
  pull_request:
    types: [opened, reopened]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:

  mention_notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - uses: Laurenfrost/mention-to-slack@latest
        with:
          configuration-path: .github/config/slack-config.yml
          repo-token: ${{ secrets.GH_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
