name: Test

on:
  push:
    branches:
      - uijong
      - yuseok
      - wonseok

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    name: Run All unit tests on Java 17

    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle # Gradle dependency caching

      - name: Setup application.properties
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Setup firebase-adminsdk-fbsvc-5d0ae449ec.json
        run: |
          echo "${{ secrets.FIREBASE_KEY_JSON }}" | base64 --decode > ./src/main/resources/seat-catcher-firebase-adminsdk-fbsvc-5d0ae449ec.json

      - name: Run tests # 전체 테스트 실행
        run: ./gradlew test